name: Java CI
on:
   push:
      branches: 
         - "**"
      tags-ignore:
         - v*
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v3
      -  name: Set up JDK 21
         uses: actions/setup-java@v3
         with:
            java-version: 21
            distribution: "liberica"
      -  name: Build with Maven
         run: mvn --no-transfer-progress package --file pom.xml
      -  name: Upload coverage report
         uses: codecov/codecov-action@v3
         with:
            token: ${{ secrets.CODECOV_TOKEN }}
