name: Perform maven release
on:
   workflow_dispatch:
jobs:
   prepare:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v3
         with:
           fetch-depth: 0
           persist-credentials: false
      -  uses: oleksiyrudenko/gha-git-credentials@v2-latest
         with:
           actor: 'Falland'
           token: '${{ secrets.GITHUB_TOKEN }}'
      -  name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
            java-version: 17
            distribution: "liberica"
      -  name: Retreive short version hash
         id: short_hash
         run: "echo \"HASH=$(git rev-parse --short HEAD)\" >> $GITHUB_OUTPUT"
   
      -  name: Retreive dev version
         id: dev_version
         run: "echo VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_OUTPUT"

      -  name: Maven release:prepare from main
         if: github.ref == 'refs/heads/main'
         run: mvn --no-transfer-progress -Dusername=$GIT_USERNAME -Dpassword=$GIT_PASSWORD release:prepare -B --file pom.xml
         env:
            GIT_USERNAME: 'Faland'
            GIT_PASSWORD: '${{ secrets.GITHUB_TOKEN }}'

      -  name: Maven release:prepare from branch
         if: github.ref != 'refs/heads/main'
         run: mvn --no-transfer-progress -Dusername=$GIT_USERNAME -Dpassword=$GIT_PASSWORD -DreleaseVersion=$(date +'%m%d')${{ steps.short_hash.outputs.HASH }} -DdevelopmentVersion=${{ steps.dev_version.outputs.VERSION }} release:prepare -B --file pom.xml
         env:
            GIT_USERNAME: 'Falland'
            GIT_PASSWORD: '${{ secrets.GITHUB_TOKEN }}'
